### ISSUE TITLE
Does FFI support iOS static library？

### ISSUE THREAD

**Issue by JackPanda8** [dart-lang/samples#78] opened 2020-11-27 02:23 UTC
as the official doc : 
**Symbols from a statically linked library can be loaded using DynamicLibrary.executable or DynamicLibrary.process.**

but i got the error: Invalid argument(s): Failed to lookup symbol (dlsym(RTLD_DEFAULT, pause_all_task): symbol not found)，

-------------here is my code--------------------------------
```
import 'dart:ffi' as ffi;
import 'dart:io';
import 'package:ffi/ffi.dart';

// C function signatures
typedef pause_all_task_t = ffi.Void Function();
typedef get_cache_instance = ffi.Pointer<ffi.Void> Function();

// Dart function signatures
typedef PauseALLTask = void Function();
typedef GetCacheInstance = ffi.Pointer<ffi.Void> Function();

// Getting a library that holds needed symbols
ffi.DynamicLibrary _lib = Platform.isAndroid
		? ffi.DynamicLibrary.open('libflash-downloader-lib.so')
		: ffi.DynamicLibrary.process();

// Looking for the functions
final PauseALLTask pauseAllTaskF = _lib
		.lookup<ffi.NativeFunction<pause_all_task_t>>('pause_all_task')
		.asFunction();
final GetCacheInstance getCacheInstanceF = _lib
		.lookup<ffi.NativeFunction<get_cache_instance>>('get_cache_instance')
		.asFunction();
```

```
#include "dart_ffi_adapter.h"
//#include "YKCacheCenter.h"
extern "C" {
attribute((visibility("default"))) attribute((used))
void* get_cache_instance(void) {
printf("my_download:调用GetCacheInstance构造单例");
void* p;
return p;
}
attribute((visibility("default"))) attribute((used))
void pause_all_task(void) {
// yk_cache::IYKCache *cache = yk_cache::GetCacheInstance();
// cache->pauseAllTask();
printf("my_download:调用pause_all_task暂停所有下载中的任务");
}
attribute((visibility("default"))) attribute((used))
void ff_pause_all_task(){
printf("my_download:call ff_pause_all_task");
}
}
```

**Comment by dcharkes** [comment] 2020-11-27 10:45
Duplicate of https://github.com/flutter/flutter/issues/71295.

**Comment by dcharkes** [comment] 2020-11-27 10:47
(I'll leave a comment on the other issue.)

**Closed by dcharkes** 2020-11-27 10:47 UTC
